
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data_dev:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  mongo_data_dev:
